spring.application.name=order-service

# Thông tin k?t n?i c? s? d? li?u
spring.datasource.url=jdbc:postgresql://localhost:5432/order_db
spring.datasource.username=admin
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# Ép Hibernate s? d?ng ?úng ph??ng th?c giao ti?p c?a PostgreSQL (S?a l?i DialectFactoryImpl)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# T? ??ng c?p nh?t b?ng trong Database
spring.jpa.hibernate.ddl-auto=update