plugins {
    id 'java'
    id 'org.springframework.boot' version '3.3.4' // Spring Boot hiện tại dùng bản 3.x, bản 4.1.1 chưa tồn tại sẽ báo lỗi
    id 'io.spring.dependency-management' version '1.1.6'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'
description = 'order-service'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

    // Sửa thành tên chuẩn của thư viện Web
    implementation 'org.springframework.boot:spring-boot-starter-web'

    // Thư viện kết nối PostgreSQL (Rất chuẩn!)
    runtimeOnly 'org.postgresql:postgresql'

    // Gom chung thành 1 thư viện test chuẩn của Spring Boot
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}